/**
 * Serializes the iframe's DOM into clean HTML, removing all bridge artifacts
 * and slide framework runtime state.
 */

/** Navigation classes added by slide frameworks (mirrors bridge.ts NAV_CLASSES) */
const SLIDE_NAV_CLASSES = [
  'active', 'current', 'present', 'visible', 'swiper-slide-active',
  'hidden', 'past', 'future', 'swiper-slide-prev', 'swiper-slide-next',
];

/**
 * Slide container selectors in priority order (mirrors bridge.ts getSlideSelector logic).
 * The first selector that matches 2+ elements is used.
 */
const SLIDE_SELECTORS = [
  '.reveal section:not(section section)',
  '.slides > section',
  '.slide',
  '.page',
  '.swiper-slide',
  '[data-slide]',
  '.step',
];

/**
 * Framework runtime elements that are dynamically generated and should be removed on save.
 * These are NEVER user-authored — they are injected by framework JS at init time.
 * Mirrors FRAMEWORK_UI_SELECTORS in bridge.ts.
 */
const FRAMEWORK_RUNTIME_SELECTORS = [
  // Reveal.js — dynamic UI and structural elements
  '.reveal > .backgrounds',
  '.reveal > .controls',
  '.reveal > .progress',
  '.reveal > .slide-number',
  '.reveal > .pause-overlay',
  '.reveal > .playback',
  '.reveal > .jump-to-slide',
  '.reveal > .speaker-notes',
  '.aria-status',
  // Swiper — navigation UI
  '.swiper-button-next',
  '.swiper-button-prev',
  '.swiper-pagination',
  '.swiper-scrollbar',
  // Impress.js — toolbar & console
  '#impress-toolbar',
  '#impress-console',
  '#impress-progressbar',
  '#impress-progress',
  // Slick — arrows, dots, structural wrappers
  '.slick-arrow',
  '.slick-prev',
  '.slick-next',
  '.slick-dots',
  // Deck.js pattern
  '.deck-status',
  '.deck-menu',
  // Generic slide controls
  '.slide-nav',
  '.slide-controls',
];

/**
 * Reset slide navigation state so the saved HTML always opens at slide 1.
 * Removes framework-injected navigation classes and visibility inline styles
 * from slide container elements, without touching user-applied styles.
 */
function resetSlideNavState(doc: Document): void {
  let slideEls: NodeListOf<Element> | null = null;
  for (const sel of SLIDE_SELECTORS) {
    const found = doc.querySelectorAll(sel);
    if (found.length > 1) { slideEls = found; break; }
  }
  if (!slideEls) return;

  slideEls.forEach((el) => {
    const htmlEl = el as HTMLElement;
    // Remove navigation classes added by slide frameworks
    SLIDE_NAV_CLASSES.forEach((cls) => htmlEl.classList.remove(cls));
    // Reset inline visibility styles used by frameworks to hide inactive slides
    if (htmlEl.style.display === 'none') htmlEl.style.display = '';
    if (htmlEl.style.visibility === 'hidden') htmlEl.style.visibility = '';
    if (htmlEl.style.opacity === '0') htmlEl.style.opacity = '';
  });

  // Restore the first-slide active state so the file opens at slide 1.
  // Simple CSS-driven decks (e.g. custom slide-deck-generator output) rely on
  // an 'active' class being present in the HTML to make the first slide visible;
  // there is no JS init that adds it programmatically. For framework-driven
  // players (Reveal.js, Swiper) the framework JS re-initializes on load anyway,
  // so the extra class is harmless.
  (slideEls[0] as HTMLElement).classList.add('active');
}

/**
 * Remove runtime-added classes from scroll animation libraries so they
 * re-initialize properly when the saved HTML is reopened.
 *
 * AOS: adds `aos-init` on library init, `aos-animate` when an element enters
 * the viewport. If present in saved HTML, AOS treats those elements as already
 * animated and skips scroll-triggering entirely on reload.
 */
function resetScrollAnimationState(doc: Document): void {
  const aosEls = doc.querySelectorAll('.aos-init, .aos-animate, [data-aos]');
  aosEls.forEach((el) => {
    el.classList.remove('aos-init', 'aos-animate');
  });
}

/**
 * Remove specific CSS properties from an element's inline style.
 * Properties matching the pattern are stripped; others are preserved.
 */
function removeStyleProps(el: HTMLElement, pattern: RegExp): void {
  const style = el.getAttribute('style');
  if (!style) return;
  const cleaned = style
    .split(';')
    .map(s => s.trim())
    .filter(s => {
      if (!s) return false;
      const prop = s.split(':')[0]?.trim();
      return prop ? !pattern.test(prop) : false;
    })
    .join('; ');
  if (cleaned) el.setAttribute('style', cleaned);
  else el.removeAttribute('style');
}

/**
 * Remove <style> tags injected at runtime by CDN libraries.
 * These are generated by JS scripts (e.g. Tailwind CDN, Google Fonts loader)
 * and don't exist in the original HTML source.
 */
function removeCdnInjectedStyles(doc: Document): void {
  doc.querySelectorAll('style').forEach(style => {
    // Skip user-authored or bridge styles (have specific attributes)
    if (style.hasAttribute('data-bridge') ||
        style.hasAttribute('data-bridge-styles') ||
        style.hasAttribute('data-bridge-class-styles')) return;

    const text = style.textContent || '';

    // Tailwind CDN: injects a massive <style> with full utility CSS
    // Identifiable by the "tailwindcss" comment header
    if (text.includes('tailwindcss') && text.includes('--tw-')) {
      style.remove();
      return;
    }

    // Tailwind CDN also injects a smaller <style> for custom config (preflight, keyframes)
    // These typically contain "--tw-" custom properties and Tailwind reset selectors
    if (text.includes('--tw-ring-offset-shadow') || text.includes('--tw-translate-x')) {
      // Only remove if it looks like auto-generated (very long, no line breaks = minified)
      if (text.length > 1000 && !text.includes('\n\n')) {
        style.remove();
        return;
      }
    }
  });
}

/**
 * Remove dynamically-generated runtime elements injected by slide frameworks.
 * These elements are created by framework JS at initialization and don't exist
 * in the original HTML source.
 */
function removeFrameworkRuntimeElements(doc: Document): void {
  for (const sel of FRAMEWORK_RUNTIME_SELECTORS) {
    doc.querySelectorAll(sel).forEach(el => el.remove());
  }
}

/**
 * Reset Reveal.js-specific runtime state on container and slide elements.
 * Only removes attributes/classes that are 100% Reveal.js internal —
 * never user-authored.
 */
function resetRevealJsState(doc: Document): void {
  const revealEl = doc.querySelector('.reveal');
  if (!revealEl) return;

  // --- <html> runtime classes ---
  doc.documentElement.classList.remove('reveal-full-page', 'reveal-print', 'no-touch');

  // --- <body> runtime classes & CSS variable styles ---
  doc.body.classList.remove('reveal-viewport');
  removeStyleProps(doc.body, /^--slide-|^--viewport-/);

  // --- .reveal container: runtime classes & attributes ---
  const revealRuntimeClasses = [
    'center', 'focused', 'has-vertical-slides', 'has-horizontal-slides',
    'ready', 'slide', 'has-dark-background', 'overview', 'rtl',
    'has-navigate-up', 'has-navigate-down', 'has-navigate-left', 'has-navigate-right',
  ];
  revealRuntimeClasses.forEach(cls => revealEl.classList.remove(cls));
  revealEl.removeAttribute('role');
  revealEl.removeAttribute('data-transition-speed');
  revealEl.removeAttribute('data-background-transition');
  (revealEl as HTMLElement).removeAttribute('style');

  // --- .slides container: remove positioning styles ---
  const slidesEl = revealEl.querySelector('.slides');
  if (slidesEl) (slidesEl as HTMLElement).removeAttribute('style');

  // --- <section> elements: runtime attributes & styles ---
  revealEl.querySelectorAll('section').forEach(section => {
    const el = section as HTMLElement;
    // Runtime-only attributes (never in source HTML)
    el.removeAttribute('hidden');
    el.removeAttribute('aria-hidden');
    el.removeAttribute('data-fragment');
    el.removeAttribute('data-previous-indexv');
    el.classList.remove('stack', 'has-dark-background');
    // Positioning styles added by Reveal.js layout engine
    removeStyleProps(el, /^top$|^display$|^transform$/);
  });

  // --- .fragment elements: runtime visibility state ---
  revealEl.querySelectorAll('.fragment').forEach(el => {
    el.classList.remove('visible', 'current-fragment');
    el.removeAttribute('data-fragment-index');
  });

  // --- Plugin-injected <style> tags (e.g. highlight.js line numbers) ---
  doc.querySelectorAll('style').forEach(style => {
    const text = style.textContent || '';
    // highlight.js line number plugin injects .hljs-ln styles
    if (text.includes('.hljs-ln') && !style.hasAttribute('data-bridge')) {
      style.remove();
    }
  });

  // --- code-wrapper: Reveal.js wraps <pre> with this class ---
  revealEl.querySelectorAll('pre.code-wrapper').forEach(pre => {
    pre.classList.remove('code-wrapper');
  });
}

/**
 * Reset Swiper-specific runtime state.
 */
function resetSwiperState(doc: Document): void {
  // .swiper container runtime classes
  doc.querySelectorAll('.swiper').forEach(el => {
    el.classList.remove('swiper-initialized', 'swiper-horizontal', 'swiper-vertical');
  });
  // .swiper-slide runtime classes
  doc.querySelectorAll('.swiper-slide').forEach(el => {
    el.classList.remove(
      'swiper-slide-active', 'swiper-slide-prev', 'swiper-slide-next',
      'swiper-slide-visible', 'swiper-slide-fully-visible',
    );
    el.removeAttribute('data-swiper-slide-index');
    el.removeAttribute('role');
    el.removeAttribute('aria-label');
    el.removeAttribute('aria-roledescription');
  });
  // Remove cloned slides (infinite loop duplicates)
  doc.querySelectorAll('.swiper-slide-duplicate').forEach(el => el.remove());
  // .swiper-wrapper transform
  doc.querySelectorAll('.swiper-wrapper').forEach(el => {
    removeStyleProps(el as HTMLElement, /^transform$|^transition/);
  });
}

/**
 * Reset Impress.js-specific runtime state.
 */
function resetImpressState(doc: Document): void {
  doc.documentElement.classList.remove('impress-supported', 'impress-enabled');
  doc.body.classList.remove('impress-on');
  // .step runtime classes
  doc.querySelectorAll('.step').forEach(el => {
    el.classList.remove('active', 'present', 'past', 'future');
  });
}

/**
 * Reset Slick carousel runtime state.
 */
function resetSlickState(doc: Document): void {
  doc.querySelectorAll('.slick-initialized').forEach(el => {
    el.classList.remove('slick-initialized', 'slick-vertical');
  });
  doc.querySelectorAll('.slick-slide').forEach(el => {
    el.classList.remove('slick-active', 'slick-current', 'slick-center');
    el.removeAttribute('data-slick-index');
    el.removeAttribute('role');
    el.removeAttribute('aria-describedby');
  });
  // Remove cloned slides
  doc.querySelectorAll('.slick-cloned').forEach(el => el.remove());
}

/**
 * Clean HTML content by removing bridge-injected elements and attributes,
 * and stripping slide framework runtime state.
 * Works on the HTML string (does not require DOM access).
 */
export function serializeCleanHtml(html: string): string {
  // Use DOMParser to parse and clean
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  // Remove bridge scripts
  const bridgeScripts = doc.querySelectorAll('script[data-bridge]');
  bridgeScripts.forEach((el) => el.parentNode?.removeChild(el));

  // Remove bridge styles
  const bridgeStyles = doc.querySelectorAll('style[data-bridge-styles]');
  bridgeStyles.forEach((el) => el.parentNode?.removeChild(el));

  // Remove bridge class styles
  const bridgeClassStyles = doc.querySelectorAll('style[data-bridge-class-styles]');
  bridgeClassStyles.forEach((el) => el.parentNode?.removeChild(el));

  // Remove bridge attributes from all elements
  const allElements = doc.querySelectorAll(
    '[data-bridge-hover], [data-bridge-selected], [data-editor-id], [contenteditable]'
  );
  allElements.forEach((el) => {
    el.removeAttribute('data-bridge-hover');
    el.removeAttribute('data-bridge-selected');
    el.removeAttribute('data-editor-id');
    el.removeAttribute('contenteditable');
  });

  // Remove runtime-injected <style> tags from CDN libraries (Tailwind CDN, etc.)
  removeCdnInjectedStyles(doc);

  // Reset slide framework navigation state so the file always opens at slide 1
  resetSlideNavState(doc);

  // Reset scroll animation library state so animations re-trigger on scroll
  resetScrollAnimationState(doc);

  // Remove dynamically-generated framework UI elements (controls, progress bars, etc.)
  removeFrameworkRuntimeElements(doc);

  // Framework-specific runtime state cleanup
  resetRevealJsState(doc);
  resetSwiperState(doc);
  resetImpressState(doc);
  resetSlickState(doc);

  // Reconstruct with DOCTYPE
  return '<!DOCTYPE html>\n' + doc.documentElement.outerHTML;
}

/**
 * Trigger download of an HTML file.
 */
export function downloadHtml(html: string, fileName: string): void {
  const cleanHtml = serializeCleanHtml(html);
  const blob = new Blob([cleanHtml], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  URL.revokeObjectURL(url);
}
